apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: insecure-container
    image: nginx
    securityContext:
      runAsUser: 0
      privileged: true
      capabilities:
        add: ["ALL"]
  hostNetwork: true
