name: Kubesec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '34 10 * * 3'

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Kubernetes YAML files
        run: |
          files=$(find . -name "*.yaml" -o -name "*.yml")
          k8s_files=""
          for file in $files; do
            if grep -q "^apiVersion:" $file && grep -q "^kind:" $file && grep -q "^metadata:" $file && grep -q "^spec:" $file; then
              k8s_files="$k8s_files\"$file\","
            fi
          done
          echo "FILE_MATRIX={\"file\": [$k8s_files]}" >> $GITHUB_ENV 

      - name: Set matrix
        run: echo "matrix=$FILE_MATRIX" >> $GITHUB_OUTPUT
        id: set-matrix

  scan:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      matrix:
        file: ${{fromJson(needs.prepare.outputs.matrix).file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: ${{ matrix.file }}
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Print kubesec-results.sarif
        run: cat kubesec-results.sarif
          
      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kubesec-results.sarif
