name: Kubesec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '34 10 * * 3'

jobs:
  lint:
    name: Kubesec
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find all yaml files
        run: find . -name "*.yaml" -o -name "*.yml" > k8s-yaml-files.txt

      - name: Run kubesec scanner
        run: |
          while IFS= read -r file
          do
            kubesec scan $file
          done < k8s-yaml-files.txt
        env:
          KUBESEC_EXIT_CODE: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kubesec-results.sarif
