name: Kubesec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '34 10 * * 3'

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find YAML files
        run: |
          files=$(find . -name "*.yaml" -o -name "*.yml")
          files_list=""
          for file in $files; do
            files_list="$files_list\"$file\","
          done
          echo "FILE_MATRIX={\"file\": [$files_list]}" >> $GITHUB_ENV 

      - name: Set matrix
        run: echo "matrix=$FILE_MATRIX" >> $GITHUB_OUTPUT
        id: set-matrix

  lint:
    needs: prepare
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      matrix:
        file: ${{fromJson(needs.prepare.outputs.matrix).file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: ${{ matrix.file }}
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kubesec-results.sarif
